# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

services:
  kafka:
    container_name: kafka
    image: dockerhub.charisma.tech/bitnami/kafka:3.6
    #network_mode: host
    ports:
      - "9092:9092"
      - "9094:9092"
      - "7071:7071"
    volumes:
      - "kafka_data:/bitnami"
      - "./kafka_files/:/opt/prometheus/"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://:9092,EXTERNAL://:9094                  #PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT         #CONTROLLER:SASL or CONTROLLER:SSL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      ## Additional configs
      - KAFKA_HEAP_OPTS=-Xmx1024m -Xms1024m
      - KAFKA_CLIENT_USERS=admin,user           #Default: user      NOTE: When running in KRaft mode, only the first user:password pair will take effect, as KRaft mode does not support SCRAM mechanism yet.
      - KAFKA_CLIENT_PASSWORDS=adminpassword,userpassword      #Default: bitnami
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CONTROLLER_USER=controller_user               # default: controller_user
      - KAFKA_CONTROLLER_PASSWORD=controller_password            # default: bitnami
      - KAFKA_KRAFT_CLUSTER_ID=o7OirS_5RlOYc4x1EH3M9w
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false       #true
      ## ACLs configs: org.apache.kafka.metadata.authorizer.StandardAuthorizer or kafka.security.authorizer.AclAuthorizer
      - KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true      #false
      - KAFKA_CFG_SUPER_USERS=User:admin          #User:CN=user;
      - EXTRA_ARGS=-javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.20.0.jar=7071:/opt/prometheus/kafka-2_0_0.yml
      - JMX_PROMETHEUS_PORT=7071
      - KAFKA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost
    
    networks:
      - kafka_data
      
      
  prometheus-kafka-monitoring:
    image: bitnami/prometheus:2.47.2-debian-11-r0
    container_name: prometheus-kafka-monitoring
    #network_mode: host
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/opt/bitnami/prometheus/conf/
    networks:
      - kafka_data
      
networks:
  kafka_data:
    driver: bridge

volumes:
   kafka_data:
     driver: local




